Traceback (most recent call last):
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\hanan\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Integers, floats, strings, booleans, and None
my_int = 10
my_float = 3.14
my_str = "Python"
my_bool = True
my_none = None

#Identifying the types of the variables
print(type(my_int)) # <class 'int'>
print(type(my_float)) # <class 'float'>
print(type(my_str)) # <class 'str'>
print(type(my_bool)) # <class 'bool'>
print(type(my_none)) # <class 'NoneType'>

#save the type of a variable in another variable
my_int_type = type(my_int)
print('Type of my_int:', my_int_type) # <class 'int'>

# Try manipulating the variables with different types
print('Multiplying my_int with it self:', my_int * my_int) # 100
print('Multiplying my_str with it self:', my_str * my_str) # Error    
------------------

----- stdout -----
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'NoneType'>
Type of my_int: <class 'int'>
Multiplying my_int with it self: 100
------------------

[31m---------------------------------------------------------------------------[39m
[31mTypeError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 21[39m
[32m     19[39m [38;5;66;03m# Try manipulating the variables with different types[39;00m
[32m     20[39m [38;5;28mprint[39m([33m'[39m[33mMultiplying my_int with it self:[39m[33m'[39m, my_int * my_int) [38;5;66;03m# 100[39;00m
[32m---> [39m[32m21[39m [38;5;28mprint[39m([33m'[39m[33mMultiplying my_str with it self:[39m[33m'[39m, [43mmy_str[49m[43m [49m[43m*[49m[43m [49m[43mmy_str[49m) [38;5;66;03m# Error    [39;00m

[31mTypeError[39m: can't multiply sequence by non-int of type 'str'

